# Function: train_model
# Description: This function trains an emulator on a portion of the data generated by the agent-based model.
# Parameters:
# - model_type: A string indicating the type of emulator to train. Must be either "GP" for Gaussian Process, or "NN" for Neural Network.
# - all_realisations: A list containing the inputs and outputs from all realisations of the agent-based model.
# - training_set: Either a string "all", indicating that all realisations should be used for training, or a number between 0 and 1 indicating the fraction of realisations to use for training.
train_model <- function(model_type, all_realisations, training_set) {
  num_realisations <- length(all_realisations)
  
  if (training_set == "all") {
    num_train_realisations <- num_realisations
  } else {
    num_train_realisations <- round(num_realisations * training_set)
  }
  
  train_realisations <- sample(all_realisations, num_train_realisations)
  
  inputs <- do.call(rbind, lapply(train_realisations, function(x) x$inputs))
  outputs_Infections <- do.call(c, lapply(train_realisations, function(x) x$outputs))
  
  # Shuffle inputs and outputs before training
  shuffled_index <- sample(nrow(inputs))
  
  inputs <- inputs[shuffled_index, ]
  outputs_Infections <- outputs_Infections[shuffled_index]
  
  train_emulator(model_type, inputs, outputs_Infections)
}